version: '3'

services:

  frontend:
    labels:
      shipyard.route: '/'
    build: 'frontend'
    volumes:
      - './frontend/src:/srv/src'
    ports:
      - '8080:8080'

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_DB: 'wishlist'
      POSTGRES_USER: 'wishlist'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432'

volumes:
  postgres:
